; CoDBase / CyberGamer / PBBans PunkBuster cvar list for Call of Duty 1.5 (last updated May 2023
; by Anglhz), the section the server enforced through pbsvuser.cfg. Kept verbatim (one edit:
; cl_maxpackets IN 60 125 for the 40-tick client). tools/gen_ruleset.py turns it into
; src/netcode/ruleset_table.h; the ruleset id is the file name. The same file is served from
; https://github.com/cod1plus/rulesets and downloaded by the client at start-up; bump the
; version below whenever you change a rule (the server publishes "<id>@<version>" and a client
; behind that version re-downloads while in game).
; version 1
pb_sv_cvar cg_bobAmplitudeDucked IN 0.0075
pb_sv_cvar cg_bobAmplitudeProne IN 0.03
pb_sv_cvar cg_bobamplitudestanding IN 0.007
pb_sv_cvar cg_bobMax IN 8
pb_sv_cvar cg_bobpitch IN 0
pb_sv_cvar cg_bobroll IN 0
pb_sv_cvar cg_bobup IN 0
pb_sv_cvar cg_bobWeaponAmplitude IN 0
pb_sv_cvar cg_bobWeaponLag IN 0
pb_sv_cvar cg_bobWeaponMax IN 0
pb_sv_cvar cg_bobWeaponRollAmplitude IN 0
pb_sv_cvar cg_centerPrintY IN 0
pb_sv_cvar cg_centertime IN 5
pb_sv_cvar cg_centerY IN 0
pb_sv_cvar cg_complaintPopUp IN 0
pb_sv_cvar cg_connectionIconSize IN 0
pb_sv_cvar cg_coronafardist IN 0
pb_sv_cvar cg_coronas IN 0
pb_sv_cvar cg_crosshairalpha IN 1
pb_sv_cvar cg_crosshairalphamin IN 0.7
pb_sv_cvar cg_crosshairdynamic IN 0
pb_sv_cvar cg_crosshairsize IN 48
pb_sv_cvar cg_draw2D IN 1
pb_sv_cvar cg_drawGun IN 1
pb_sv_cvar cg_drawSoundOverlay IN 0
pb_sv_cvar cg_errordecay IN 100
pb_sv_cvar cg_fov IN 80
pb_sv_cvar cg_gibs IN 0
pb_sv_cvar cg_goreDetail IN 0
pb_sv_cvar cg_gun IN 0
pb_sv_cvar cg_gun_move_f IN 0
pb_sv_cvar cg_gun_move_minspeed IN 0
pb_sv_cvar cg_gun_move_r IN 0
pb_sv_cvar cg_gun_move_rate IN 0
pb_sv_cvar cg_gun_move_u IN 0
pb_sv_cvar cg_gun_ofc_u IN 0
pb_sv_cvar cg_gun_ofs_f IN 0
pb_sv_cvar cg_gun_ofs_r IN 0
pb_sv_cvar cg_gun_ofs_u IN 0
pb_sv_cvar cg_gun_rot_minspeed IN 0
pb_sv_cvar cg_gun_rot_p IN 0
pb_sv_cvar cg_gun_rot_r IN 0
pb_sv_cvar cg_gun_rot_rate IN 0
pb_sv_cvar cg_gun_rot_y IN 0
pb_sv_cvar cg_gunX IN 0
pb_sv_cvar cg_gunY IN 0
pb_sv_cvar cg_gunZ IN 0
pb_sv_cvar cg_hudDamageIconHeight IN 64
pb_sv_cvar cg_hudDamageIconHeight IN 64
pb_sv_cvar cg_hudDamageIconInScope IN 0
pb_sv_cvar cg_hudDamageIconInScope IN 0
pb_sv_cvar cg_hudDamageIconOffset IN 32
pb_sv_cvar cg_hudDamageIconOffset IN 32
pb_sv_cvar cg_hudDamageIconTime IN 2000
pb_sv_cvar cg_hudDamageIconTime IN 2000
pb_sv_cvar cg_hudDamageIconWidth IN 128
pb_sv_cvar cg_hudDamageIconWidth IN 128
pb_sv_cvar cg_hudObjectiveMaxHeight IN 70
pb_sv_cvar cg_hudObjectiveMaxRange IN 2048
pb_sv_cvar cg_hudObjectiveMinAlpha IN 1
pb_sv_cvar cg_hudStanceFlash_b IN 0.3
pb_sv_cvar cg_hudStanceFlash_g IN 1.0
pb_sv_cvar cg_hudStanceFlash_r IN 1.0
pb_sv_cvar cg_impactPrediction IN 0
pb_sv_cvar cg_impactVibration IN 0
pb_sv_cvar cg_nopredict IN 0
pb_sv_cvar cg_noprojectiletrail IN 0
pb_sv_cvar cg_norender IN 0
pb_sv_cvar cg_oldPlasma IN 0
pb_sv_cvar cg_oldRail IN 0
pb_sv_cvar cg_oldRocket IN 0
pb_sv_cvar cg_shadows IN 0 1
pb_sv_cvar cg_smoke_sg IN 0
pb_sv_cvar cg_smokegrowth_gl IN 0
pb_sv_cvar cg_smokegrowth_rl IN 0
pb_sv_cvar cg_smokeradius_gl IN 0
pb_sv_cvar cg_smokeradius_rl IN 0
pb_sv_cvar cg_stereosparation IN 0 0.6
pb_sv_cvar cg_thirdperson IN 0
pb_sv_cvar cg_weaponCycleDelay IN 0
pb_sv_cvar cg_weaponMenuFast IN 0
pb_sv_cvar cg_weaponSelectTime IN 0
pb_sv_cvar cg_viewsize IN 100
pb_sv_cvar ch_3waveFont IN 0
pb_sv_cvar ch_ColorLocations IN 0
pb_sv_cvar ch_crosshairColor IN 0
pb_sv_cvar ch_CrosshairNamesLeft IN 0
pb_sv_cvar ch_crosshairTeamInfo IN 0
pb_sv_cvar ch_drawFlagNames IN 0
pb_sv_cvar ch_drawHealthMeters IN 0
pb_sv_cvar ch_drawPickup IN 0
pb_sv_cvar ch_drawSpeed IN 0
pb_sv_cvar ch_FilterLocationsTeamchat IN 0
pb_sv_cvar ch_font IN 0
pb_sv_cvar ch_fragMessage IN 0
pb_sv_cvar ch_graphs IN 0
pb_sv_cvar ch_Obituaries IN 0
pb_sv_cvar ch_pickupitem IN 0
pb_sv_cvar ch_statusbarformat IN 0
pb_sv_cvar ch_statusbarStyle IN 0
pb_sv_cvar ch_teambackground IN 0
pb_sv_cvar ch_TeamchatOnly IN 0
pb_sv_cvar ch_teamcrosshairhealth IN 0
pb_sv_cvar ch_Teamoverlay IN 0
pb_sv_cvar ch_weaponList IN 0
pb_sv_cvar ch_weaponListBackground IN 0
pb_sv_cvar ch_weaponListDrawAll IN 0
pb_sv_cvar ch_weaponListFlash IN 0
pb_sv_cvar ch_weaponswitch IN 0
pb_sv_cvar cl_anglespeedkey IN 1.5
pb_sv_cvar cl_avidemo IN 0
pb_sv_cvar cl_forceavidemo IN 0
pb_sv_cvar cl_freelook IN 1
pb_sv_cvar cl_maxpackets IN 30 100
pb_sv_cvar cl_nodelta IN 0
pb_sv_cvar cl_pitchspeed IN 140
pb_sv_cvar cl_punkbuster IN 1
pb_sv_cvar cl_timenudge IN 0
pb_sv_cvar cl_yawspeed IN 140
pb_sv_cvar cm_noCurves IN 0
pb_sv_cvar cm_playerCurveClip IN 1
pb_sv_cvar com_blindlyLoadDLLs IN 0
pb_sv_cvar com_maxfps IN 40 250
pb_sv_cvar com_maxfps OUT 0.000001 39
pb_sv_cvar com_maxfps OUT 334 1000
pb_sv_cvar con_autoclear IN 0
pb_sv_cvar con_boldgamemessagetime IN 8
pb_sv_cvar con_debug IN 0
pb_sv_cvar con_inputBoxColor IN 0
pb_sv_cvar con_inputHintBoxColor IN 0
pb_sv_cvar con_minicon IN 0
pb_sv_cvar con_miniconlines IN 5
pb_sv_cvar con_minicontime IN 4
pb_sv_cvar con_notifytime IN 0
pb_sv_cvar con_outputBarColor IN 0
pb_sv_cvar con_outputSliderColor IN 0
pb_sv_cvar con_outputWindowColor IN 0
pb_sv_cvar con_restricted IN 0
pb_sv_cvar developer IN 0
pb_sv_cvar ecw_map IN 0
pb_sv_cvar eg_enableOSPhud IN 0
pb_sv_cvar enemy_model IN 0
pb_sv_cvar ex_interp IN 0
pb_sv_cvar fallback IN 0
pb_sv_cvar fixedtime IN 0
pb_sv_cvar forcefps IN 0
pb_sv_cvar forcepowers IN 0
pb_sv_cvar fx_count IN 0
pb_sv_cvar fx_debug IN 0
pb_sv_cvar fx_debugBolt IN 0
pb_sv_cvar fx_draw IN 1
pb_sv_cvar fx_enable IN 1
pb_sv_cvar fx_freeze IN 0
pb_sv_cvar fx_profile IN 0
pb_sv_cvar g_debuganim IN 0
pb_sv_cvar g_debugBullets IN 0
pb_sv_cvar g_debugDamage IN 0
pb_sv_cvar g_debugLocDamage IN 0
pb_sv_cvar g_debugShowHit IN 0
pb_sv_cvar graphheight IN 32
pb_sv_cvar graphscale IN 1
pb_sv_cvar gt_simpleScoring IN 0
pb_sv_cvar gun_x IN 0
pb_sv_cvar gun_y IN 0
pb_sv_cvar gun_z IN 0
pb_sv_cvar m_pitch OUT -0.011 0.011
pb_sv_cvar m_yaw IN 0.022
pb_sv_cvar match_latejoin IN 0
pb_sv_cvar match_minplayers IN 0
pb_sv_cvar match_mutespecs IN 0
pb_sv_cvar match_readypercent IN 0
pb_sv_cvar match_shuffle IN 0
pb_sv_cvar match_swap IN 0
pb_sv_cvar match_timeoutcount IN 0
pb_sv_cvar match_timeoutlength IN 0
pb_sv_cvar match_warmupDamage IN 0
pb_sv_cvar mss_q3fs IN 1
pb_sv_cvar osp_autoRecord IN 0
pb_sv_cvar osp_autoScreenshot IN 0
pb_sv_cvar osp_drawClock IN 0
pb_sv_cvar osp_drawCrosshairInfo IN 0
pb_sv_cvar osp_drawTeamOverlay IN 0
pb_sv_cvar osp_numericalHealth IN 0
pb_sv_cvar osp_oldConsole IN 0
pb_sv_cvar osp_oldScoreboard IN 0
pb_sv_cvar osp_simpleHud IN 0
pb_sv_cvar osp_tracerDistance IN 0
pb_sv_cvar osp_useKeyForLadders IN 0
pb_sv_cvar pb_sleep IN 0 500
pb_sv_cvar pmove_fixed IN 0
pb_sv_cvar pmove_msec IN 8
pb_sv_cvar r_colorMipLevels IN 0
pb_sv_cvar r_debugEntLight IN 0
pb_sv_cvar r_debugSort IN 0
pb_sv_cvar r_diffusesunquality IN 2
pb_sv_cvar r_diffusesunsteps IN 3
pb_sv_cvar r_displayrefresh OUT 0.1 59
pb_sv_cvar r_drawBModels IN 1
pb_sv_cvar r_drawdecals IN 0
pb_sv_cvar r_drawentities IN 1
pb_sv_cvar r_drawprimcap IN 0
pb_sv_cvar r_drawprimfloor IN 0
pb_sv_cvar r_drawSModels IN 1
pb_sv_cvar r_drawWorld IN 1
pb_sv_cvar r_drawXModels IN 1
pb_sv_cvar r_entfullBright IN 0
pb_sv_cvar r_entMinLight IN .15
pb_sv_cvar r_faceplanecull IN 0
pb_sv_cvar r_fastsky IN 0
pb_sv_cvar r_flareFadeIn IN .2
pb_sv_cvar r_flareFadeOut IN .2
pb_sv_cvar r_flares IN 1
pb_sv_cvar r_flareSize IN 96
pb_sv_cvar r_forceLod IN 0
pb_sv_cvar r_fullbright IN 0
pb_sv_cvar r_gamma IN 0 3
pb_sv_cvar r_graymap IN 0
pb_sv_cvar r_highLodDist IN -1
pb_sv_cvar r_ignorehwgamma IN 0
pb_sv_cvar r_intensity IN 1
pb_sv_cvar r_lightgamma IN 0
pb_sv_cvar r_lightmap IN 0
pb_sv_cvar r_lightningSegmentLength IN 0
pb_sv_cvar r_lightTweakAmbient IN 0 0.1
pb_sv_cvar r_lightTweakAmbientColor IN 0
pb_sv_cvar r_lightTweakDiffuseFraction IN 0
pb_sv_cvar r_lightTweakSunColor IN 0
pb_sv_cvar r_lightTweakSunDiffuseColor IN 0
pb_sv_cvar r_lightTweakSunDirection IN 0
pb_sv_cvar r_lightTweakSunLight IN 0
pb_sv_cvar r_lockpvs IN 0
pb_sv_cvar r_lodbias IN -200 0
pb_sv_cvar r_lodcap IN 0
pb_sv_cvar r_lodscale IN 0 4
pb_sv_cvar r_lodViewDist IN 0
pb_sv_cvar r_lodviewmodelcap IN 0
pb_sv_cvar r_lowestLodDist IN 0
pb_sv_cvar r_lowLodDist IN 0
pb_sv_cvar r_measureOverdraw IN 0
pb_sv_cvar r_mediumLodDist IN 0
pb_sv_cvar r_minEntLightIntensity IN 0.02
pb_sv_cvar r_nobind IN 0
pb_sv_cvar r_nocull IN 0
pb_sv_cvar r_noportals IN 0
pb_sv_cvar r_norefresh IN 0
pb_sv_cvar r_nv_fogdist_mode INCLUDE nv
pb_sv_cvar r_offsetfactor IN -1
pb_sv_cvar r_offsetunits IN -2
pb_sv_cvar r_optimize IN 1
pb_sv_cvar r_optimizetextures IN 2
pb_sv_cvar r_optimizeworld IN 1
pb_sv_cvar r_overBrightBits IN 0 1
pb_sv_cvar r_picmip IN 0 3
pb_sv_cvar r_picmip2 IN 0 3
pb_sv_cvar r_picmip2 IN 0 3
pb_sv_cvar r_polygonOffsetBias IN -1 16
pb_sv_cvar r_polygonOffsetScale IN -1 4
pb_sv_cvar r_portalOnly IN 0
pb_sv_cvar r_profileDrawElements IN 0
pb_sv_cvar r_showaabbtrees IN 0
pb_sv_cvar r_showCullBModels IN 0
pb_sv_cvar r_showCullSModels IN 0
pb_sv_cvar r_showCullXModels IN 0
pb_sv_cvar r_showLeafLights IN 0
pb_sv_cvar r_shownormals IN 0
pb_sv_cvar r_showportals IN 0
pb_sv_cvar r_showsky IN 0
pb_sv_cvar r_showsurfcounts IN 0
pb_sv_cvar r_showtricounts IN 0
pb_sv_cvar r_showtris IN 0
pb_sv_cvar r_singlecell IN 0
pb_sv_cvar r_singleShader IN 0
pb_sv_cvar r_skipBackEnd IN 0
pb_sv_cvar r_softwareGL IN 0
pb_sv_cvar r_speeds IN 0
pb_sv_cvar r_ssCheap IN 0
pb_sv_cvar r_suntest IN 0
pb_sv_cvar r_texturemode INCLUDE GL_LINEAR_MIPMAP_
pb_sv_cvar r_uifullscreen IN 0
pb_sv_cvar r_xdebug IN 0
pb_sv_cvar r_zfar IN 0
pb_sv_cvar r_znear IN 4
pb_sv_cvar r_znear_depthhack IN 0.1
pb_sv_cvar rate IN 25000
pb_sv_cvar seta skill_medic IN 0
pb_sv_cvar skill_battlesense IN 0
pb_sv_cvar skill_covertops IN 0
pb_sv_cvar skill_engineer IN 0
pb_sv_cvar skill_fieldops IN 0
pb_sv_cvar skill_heavyweapons IN 0
pb_sv_cvar skill_lightweapons IN 0
pb_sv_cvar snaps IN 20 40
pb_sv_cvar team_maxflamers IN 0
pb_sv_cvar team_maxMg42s IN 0
pb_sv_cvar team_maxMines IN 0
pb_sv_cvar team_maxmortars IN 0
pb_sv_cvar team_maxPanzers IN 0
pb_sv_cvar team_maxplayers IN 0
pb_sv_cvar team_maxriflegrenades IN 0
pb_sv_cvar ui_rate IN 0
pb_sv_cvar ui_sensitivity IN 0
pb_sv_cvar ui_showtooltips IN 0
pb_sv_cvar ui_team_fraglimit IN 0
pb_sv_cvar ui_team_friendly IN 0
pb_sv_cvar ui_team_timelimit IN 0
pb_sv_cvar ui_teamArenaFirstRun IN 0
pb_sv_cvar ui_tourney_fraglimit IN 0
pb_sv_cvar ui_tourney_timelimit IN 0
pb_sv_cvar w_aimbot IN 0
pb_sv_cvar w_alliebarcolor IN 0
pb_sv_cvar w_allieringcolor IN 0
pb_sv_cvar w_antirecoil IN 0
pb_sv_cvar w_autobash IN 0
pb_sv_cvar w_autolean IN 0
pb_sv_cvar w_barhack IN 0
pb_sv_cvar w_clearscope IN 0
pb_sv_cvar w_conlinecolor IN 0
pb_sv_cvar w_contextcolor IN 0
pb_sv_cvar w_contitlecolor IN 0
pb_sv_cvar w_crosshair IN 0
pb_sv_cvar w_crosshaircolor IN 0
pb_sv_cvar w_fire IN 0
pb_sv_cvar w_fovx IN 0
pb_sv_cvar w_fovy IN 0
pb_sv_cvar w_germanbarcolor IN 0
pb_sv_cvar w_germanringcolor IN 0
pb_sv_cvar w_modelcolor IN 0
pb_sv_cvar w_models IN 0
pb_sv_cvar w_nofog IN 0
pb_sv_cvar w_ringhack IN 0
pb_sv_cvar w_skycolor IN 0
pb_sv_cvar w_skyhack IN 0
pb_sv_cvar w_stealth IN 0
pb_sv_cvar w_vehicleesp IN 0
pb_sv_cvar w_whitewalls IN 0
pb_sv_cvar weaponmask IN 0
pb_sv_cvar weight_gametype_items IN 0
pb_sv_cvar weight_pickup_item_ARMOR_step IN 0
pb_sv_cvar weight_pickup_item_INFRARED IN 0
pb_sv_cvar weight_pickup_item_NIGHTVISION IN 0
pb_sv_cvar weight_pickup_weapon_AK_74 IN 0
pb_sv_cvar weight_pickup_weapon_AN_M14 IN 0
pb_sv_cvar weight_pickup_weapon_M15 IN 0
pb_sv_cvar weight_pickup_weapon_M19 IN 0
pb_sv_cvar weight_pickup_weapon_M3A1 IN 0
pb_sv_cvar weight_pickup_weapon_M4 IN 0
pb_sv_cvar weight_pickup_weapon_M590 IN 0
pb_sv_cvar weight_pickup_weapon_M60 IN 0
pb_sv_cvar weight_pickup_weapon_M84 IN 0
pb_sv_cvar weight_pickup_weapon_microuzi IN 0
pb_sv_cvar weight_pickup_weapon_MM_1 IN 0
pb_sv_cvar weight_pickup_weapon_MP5 IN 0
pb_sv_cvar weight_pickup_weapon_MSG90A1 IN 0
pb_sv_cvar weight_pickup_weapon_RPG_7 IN 0
pb_sv_cvar weight_pickup_weapon_SIG551 IN 0
pb_sv_cvar weight_pickup_weapon_silvertalon IN 0
pb_sv_cvar weight_pickup_weapon_SMOHG92 IN 0
pb_sv_cvar weight_pickup_weapon_US_SOCOM IN 0
pb_sv_cvar weight_pickup_weapon_USAS_12 IN 0
pb_sv_cvar weight_realisticdamage_step IN 0
pb_sv_cvar weight_weapon_knife IN 0
pb_sv_cvar win_noalttab IN 0
pb_sv_cvar winvoice_mic_mute IN 0
pb_sv_cvar winvoice_mic_reclevel IN 0
pb_sv_cvar winvoice_mic_scaler IN 0
pb_sv_cvar winvoice_save_voice IN 0
pb_sv_cvar zoomfov IN 0
pb_sv_cvar do_attack IN 0 0
pb_sv_cvar do_reload IN 0 0
pb_sv_cvar do_melee EXCLUDE "melee"
pb_sv_cvar d0_melee EXCLUDE "MELEE"
pb_sv_cvar mouse2 EXCLUDE "VSTR"
pb_sv_cvar d0_reload EXCLUDE "RELOAD"
pb_sv_cvar d0_attack EXCLUDE "ATTACK"
pb_sv_cvar "bind N" EXCLUDE "vstr"
pb_sv_cvar cg_crosshairalphamin IN 0.7
pb_sv_cvar cg_crosshairalpha IN 1
pb_sv_cvar cg_draw2D IN 1
pb_sv_cvar cg_gun_ofc_u IN 0
pb_sv_cvar cg_hudObjectiveMinAlpha IN 1
pb_sv_cvar cg_norender IN 0
pb_sv_cvar cg_shadows IN 0 1
pb_sv_cvar cg_thirdpersonangle IN 0
pb_sv_cvar cg_thirdpersonrange IN 120
pb_sv_cvar cg_viewsize IN 100
pb_sv_cvar cl_avidemo IN 0
pb_sv_cvar cl_freelook IN 1
pb_sv_cvar cl_maxpackets IN 60 125
pb_sv_cvar cl_nodelta IN 0
pb_sv_cvar cm_noCurves IN 0
pb_sv_cvar com_maxfps IN 60 250
pb_sv_cvar com_maxfps OUT 0.000001 59
pb_sv_cvar developer IN 0
pb_sv_cvar fx_count IN 0
pb_sv_cvar fx_draw IN 1
pb_sv_cvar fx_enable IN 1
pb_sv_cvar fx_freeze IN 0
pb_sv_cvar m_pitch OUT -0.015 0.015
pb_sv_cvar m_yaw IN 0.022
pb_sv_cvar pmove_fixed IN 0
pb_sv_cvar pmove_msec IN 8
pb_sv_cvar r_debugEntLight IN 0
pb_sv_cvar r_debugSort IN 0
pb_sv_cvar r_displayrefresh OUT 0.1 59
pb_sv_cvar r_drawBModels IN 1
pb_sv_cvar r_drawXModels IN 1
pb_sv_cvar r_fastsky IN 0
pb_sv_cvar r_fullbright IN 0
pb_sv_cvar r_graymap IN 0
pb_sv_cvar r_highLodDist IN -1
pb_sv_cvar r_ignorehwgamma IN 0
pb_sv_cvar r_lockPvs IN 0
pb_sv_cvar r_lodbias IN 0
pb_sv_cvar r_lodscale IN 0 1
pb_sv_cvar r_lowLodDist IN 0
pb_sv_cvar r_lodViewDist IN 0
pb_sv_cvar r_mapoverbrightbits IN 0 2
pb_sv_cvar r_measureOverdraw IN 0
pb_sv_cvar r_mediumLodDist IN 0
pb_sv_cvar r_nobind IN 0
pb_sv_cvar r_nocull IN 0
pb_sv_cvar r_noportals IN 0
pb_sv_cvar r_norefresh IN 0
pb_sv_cvar r_nv_fog_dist IN 0
pb_sv_cvar r_nv_fogdist_mode INCLUDE nv
pb_sv_cvar r_nv_fogdist_mode in gl_eye_radial_nv
pb_sv_cvar r_optimize IN 1
pb_sv_cvar r_optimizeworld IN 1
pb_sv_cvar r_optimizetextures IN 2
pb_sv_cvar r_portalOnly IN 0
pb_sv_cvar r_profileDrawElements IN 0
pb_sv_cvar r_showaabbtrees IN 0
pb_sv_cvar r_showCullBModels IN 0
pb_sv_cvar r_showCullSModels IN 0
pb_sv_cvar r_shownormals IN 0
pb_sv_cvar r_showPortals IN 0
pb_sv_cvar r_showsky IN 0
pb_sv_cvar r_showSurfCounts IN 0
pb_sv_cvar r_showTriCounts IN 0
pb_sv_cvar r_singleCell IN 0
pb_sv_cvar r_singleShader IN 0
pb_sv_cvar r_skipBackEnd IN 0
pb_sv_cvar r_speeds IN 0
pb_sv_cvar r_suntest IN 0
pb_sv_cvar r_uifullscreen IN 0
pb_sv_cvar r_weightMipMaps IN 0
pb_sv_cvar r_xdebug EXCLUDE axes
pb_sv_cvar r_xdebug EXCLUDE boxes
pb_sv_cvar r_xdebug EXCLUDE both
pb_sv_cvar r_xdebug IN 0
pb_sv_cvar r_zfar IN 0
pb_sv_cvar r_znear IN 4
pb_sv_cvar r_znear_depthhack IN 0.1
pb_sv_cvar set exclude wallhack
pb_sv_cvar set exclude aim
pb_sv_cvar set exclude radar
pb_sv_cvar sjs_aim IN 0
pb_sv_cvar sjs_aim EXCLUDE 0
pb_sv_cvar sjs_shoot IN 0
pb_sv_cvar sjs_shoot EXCLUDE 0
pb_sv_cvar sjs_wall IN 0
pb_sv_cvar sjs_wall EXCLUDE 0
pb_sv_cvar viewlog IN 0
pb_sv_cvar wallhack exclude 1
pb_sv_cvar aim exclude 1
pb_sv_cvar wallhack exclude 2
pb_sv_cvar wallhack exclude 0
pb_sv_cvar aim exclude 0
pb_sv_cvar exec exclude .
pb_sv_cvar wwall1 IN 0**********************************************
pb_sv_cvar bs_showCullXModels IN 0
pb_sv_cvar bs_showsurfcounts IN 0
pb_sv_cvar z_showCullXModels IN 0
pb_sv_cvar z_showsurfcounts IN 0
pb_sv_cvar b_wallhack IN 0
pb_sv_cvar cod_predict IN 0
pb_sv_cvar cod_names IN 0
pb_sv_cvar cod_nofog IN 0
pb_sv_cvar cod_shoot IN 0
pb_sv_cvar cod_weapons IN 0
pb_sv_cvar _aim_key IN 0
pb_sv_cvar _aimfov IN 0
pb_sv_cvar _aimkey IN 0
pb_sv_cvar _aimpredict IN 0
pb_sv_cvar _aimshoot IN 0
pb_sv_cvar _aimvecz IN 0
pb_sv_cvar _autoshoot IN 0
pb_sv_cvar _killsounds IN 0
pb_sv_cvar _radar IN 0
pb_sv_cvar _wall IN 0
pb_sv_cvar _wallhack IN 0
pb_sv_cvar _491ebf653aed411e IN 0
pb_sv_cvar bot_aim IN 0
pb_sv_cvar bot_distance IN 0
pb_sv_cvar bot_radar IN 0
pb_sv_cvar bot_wallhack IN 0
pb_sv_cvar cod_aimbot IN 0
pb_sv_cvar cod_autoshoot IN 0
pb_sv_cvar cod_fov IN 0
pb_sv_cvar cod_radar IN 0
pb_sv_cvar cod_wallhack IN 0
pb_sv_cvar cu_aim_key IN 0
pb_sv_cvar cu_aimvecs IN 0
pb_sv_cvar cu_wallhack IN 0
pb_sv_cvar hax_aim IN 0
pb_sv_cvar hax_aimbot IN 0
pb_sv_cvar hax_distance IN 0
pb_sv_cvar hax_radar IN 0
pb_sv_cvar hax_shoot IN 0
pb_sv_cvar hax_stats IN 0
pb_sv_cvar hax_wallhack IN 0
pb_sv_cvar ic_aim_key IN 0
pb_sv_cvar ic_radar_width IN 0
pb_sv_cvar mom_aimbot IN 0
pb_sv_cvar mom_radar IN 0
pb_sv_cvar mom_stats IN 0
pb_sv_cvar mom_wallhack IN 0
pb_sv_cvar orgy_aim_fov IN 0
pb_sv_cvar orgy_aim_pingpredict IN 0
pb_sv_cvar orgy_defaultSens IN 0
pb_sv_cvar orgy_radar_range IN 0
pb_sv_cvar orgy_serverkill IN 0
pb_sv_cvar orgy_wallhack IN 0
pb_sv_cvar vec_prone IN 0
pb_sv_cvar w_barhack in 0
pb_sv_cvar w_chams
pb_sv_cvar w_nofog in 0
